[workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[environments]
default = ["rust", "python"]
python = ["python"]

[feature.rust.dependencies]
rust = "*"
rust-src = "*"
sccache = "*"

[feature.python.dependencies]
python = "*"
matplotlib = "*"
xeus-python = "*"
